[versions]
agp = "8.1.3"
dagger = "2.48.1"
kotlin = "1.9.20"
ksp = "1.9.20-1.0.14"
coreKtx = "1.12.0"
appcompat = "1.6.1"
material = "1.10.0"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
hiltAndroid = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hiltCompiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
material = { module = "com.google.android.material:material", version.ref = "material" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
hiltAndroidGradlePlugin = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

